version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: main.py
      # set FLASK_APP=app.py
      # flask run
